version: '3.9'

services:
  app:
    build: .
    container_name: cesizen-app-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_dev}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: cesizen-db-dev
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME_dev}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cesizen-phpmyadmin-dev
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
