version: '3.9'

services:
  app:
    build: .
    container_name: cesizen-app-test
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=test
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_test}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: cesizen-db-test
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME_test}
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cesizen-phpmyadmin-test
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data_test:

networks:
  app-network:
    driver: bridge
