version: '3.9'

services:
  app:
    build: .
    container_name: cesizen-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_prod}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - app-network-prod
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: cesizen-db-prod
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME_prod}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - app-network-prod

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cesizen-phpmyadmin-prod
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network-prod

volumes:
  mysql_data_prod:

networks:
  app-network-prod:
    driver: bridge
