name: CI/CD Docker

on:
  push:
    branches:
      - main       
      - develop    
      - test       

env:
  IMAGE_NAME: matheo2004/monapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.ref_name }} -f api/Dockerfile .
          docker push $IMAGE_NAME:${{ github.ref_name }}


  deploy_dev:
    needs: build
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy DEV with Docker Compose
        run: docker compose -f api/docker-compose.dev.yml up -d --build

  test:
    needs: build
    if: github.ref_name == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Tests with Docker Compose
        run: |
          docker compose -f api/docker-compose.test.yml up -d --build
          docker compose -f api/docker-compose.test.yml down

  deploy_prod:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy PROD with Docker Compose
        run: docker compose -f api/docker-compose.prod.yml up -d --build
