name: CI/CD Docker

on:
  push:
    branches:
      - main      
      - test       

env:
  IMAGE_NAME: ghcr.io/matheol08/projet_cesizen

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Install dependencies
        run: npm install
      - name: Buildgit 
        run: npm run build
     



  test:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run Vitest
        run: npm run test

  deploy-image:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [build-and-push-image, test]
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
          cd Projet_CESIZen/api && \
          sudo docker-compose -f docker-compose.prod.yml up -d --pull always"
